import express from "express";
import productRouter from "./product.route.js";
import productTypeRouter from "./productType.route.js";
import countryRouter from "./country.route.js";
import branchRouter from "./branch.route.js";
import currencyRouter from "./currency.route.js";
import adrressRouter from "./address.route.js";
import userRouter from "./user.route.js";
import userTypeRouter from "./userType.route.js";
import passwordHistoryRouter from "./passwordHistory.route.js";
import passwordHashRouter from "./passwordHash.route.js";
import communicationTypeRouter from "./communicationType.route.js";
import communicationMethodRouter from "./communicationMethod.route.js";
import communicationTemplateRouter from "./communicationTemplate.route.js";
import communicationStatusRouter from "./communicationStatus.route.js";
import communicationRequestRouter from "./communicationRequest.route.js";
import confirmationTokenTypeRouter from "./confirmationTokenType.route.js";
import confirmationTokenRouter from "./confirmationToken.route.js";
import oneTimePinRouter from "./oneTimePin.route.js";
import authRouter from "./auth.route.js";
import genderRouter from "./gender.route.js";

const router = express.Router();
router.use("/api/auth", authRouter);

router.use("/api/products", productRouter);
router.use("/api/product-types", productTypeRouter);
router.use("/api/countries", countryRouter);
router.use("/api/branches", branchRouter);
router.use("/api/currencies", currencyRouter);
router.use("/api/addresses", adrressRouter);
router.use("/api/users", userRouter);
router.use("/api/password-histories", passwordHistoryRouter);
router.use("/api/password-hashes", passwordHashRouter);
router.use("/api/user-types", userTypeRouter);
router.use("/api/communication-types", communicationTypeRouter);
router.use("/api/communication-methods", communicationMethodRouter);
router.use("/api/communication-templates", communicationTemplateRouter);
router.use("/api/communication-statuses", communicationStatusRouter);
router.use("/api/communication-requests", communicationRequestRouter);
router.use("/api/confirmation-token-types", confirmationTokenTypeRouter);
router.use("/api/confirmation-token", confirmationTokenRouter);
router.use("/api/one-time-pins", oneTimePinRouter);
router.use("/api/genders", genderRouter);

export default router;
